### ISSUE TITLE
Default public storage doesn't work with default Apache rewrite

### ISSUE THREAD

**Issue by MrPetovan** [dansup/pixelfed#141]
I posted my first picture on https://pixelfed.mrpetovan.com/p/MrPetovan/1, unfortunately the image doesn't show.

The URL is https://pixelfed.mrpetovan.com/storage/m/e64c75f2f4e9a621bb7c43ec9b04a165add6493b/327b257390c5ee5a4aa50b9b36b465ce9f170376/Hw2ysT4w6iQ5C9eLsU2KtIPsRFIHB2bVlKvMnKyo.jpeg

The existing path is
`/path/to/pixelfed/storage/app/public/m/e64c75f2f4e9a621bb7c43ec9b04a165add6493b/327b257390c5ee5a4aa50b9b36b465ce9f170376/Hw2ysT4w6iQ5C9eLsU2KtIPsRFIHB2bVlKvMnKyo.jpeg`

I'm not sure how to fix this since the storage path isn't under the `DocumentRoot` in `/path/to/pixelfed/public`.

Environment:
- Debian 9
- PHP 7.2.5
- Apache 2.4.25

**Comment by neilalexander** [comment]
I fixed this by using an alias:
```
DocumentRoot /var/www/pixelfed/public
Alias /storage /var/www/pixelfed/storage/app/public
```

**Comment by dansup** [comment]
Run

```php
php artisan storage:link
```

in project root

**Comment by MrPetovan** [comment]
This worked.
