### ISSUE TITLE
uploading keeps failing

### ISSUE THREAD

**Issue by veb** [dansup/pixelfed#61]
I'm having an issue uploading this image for example:

![20171125_114317](https://user-images.githubusercontent.com/376245/40824905-f929a28a-65c9-11e8-9bb8-5c06acf35960.jpg)

I'm on Chrome, Version 66.0.3359.181 (Official Build) (64-bit) MacOS. 

It seems to say in the status bar (quite slowly) "Uploading... 2%... 4%... 20%... 100%", then it restarts.

Same behaviour is happening for me in Firefox.

The latency isn't _too_ abnormal from NZ: 

```
PING pixelfed.social (104.27.185.178): 56 data bytes
64 bytes from 104.27.185.178: icmp_seq=0 ttl=54 time=427.454 ms
64 bytes from 104.27.185.178: icmp_seq=1 ttl=54 time=327.608 ms
64 bytes from 104.27.185.178: icmp_seq=2 ttl=54 time=380.270 ms
64 bytes from 104.27.185.178: icmp_seq=3 ttl=54 time=328.539 ms
64 bytes from 104.27.185.178: icmp_seq=4 ttl=54 time=328.699 ms
64 bytes from 104.27.185.178: icmp_seq=5 ttl=54 time=342.959 ms
Request timeout for icmp_seq 6
64 bytes from 104.27.185.178: icmp_seq=7 ttl=54 time=383.688 ms
64 bytes from 104.27.185.178: icmp_seq=8 ttl=54 time=402.560 ms
64 bytes from 104.27.185.178: icmp_seq=9 ttl=54 time=328.266 ms
^C
--- pixelfed.social ping statistics ---
10 packets transmitted, 9 packets received, 10.0% packet loss
round-trip min/avg/max/stddev = 327.608/361.116/427.454/35.960 ms
```

Can upload from `/timeline/public` but not `/timeline`

**Comment by kpcyrd** [comment]
hey @veb, this issue might be difficult to analyse, are there any errors in your browsers developer tools? Those are very useful for those sort of issues. Thanks!

**Comment by dansup** [comment]
@veb and I tested this, I was able to upload the image fine. I think it might be browser or latency related. If you encounter this again, please let me know.
